### ISSUE TITLE
US 5 - Create Admin Panel

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#33]
As an admin, I want to be able to manage all user profiles, job postings, and track activities on the platform.

Description: Create a management interface to track activities such as new job postings, new applicants and user profiles.

Acceptance Criteria:

An admin dashboard is designed and implemented, providing access to user profiles, job postings, and activity logs.
CRUD (Create, Read, Update, Delete) operations are implemented for user profiles and job postings.
The admin panel allows for managing user profiles, including creating, updating, and deleting user accounts.
The admin panel tracks and logs user activities, providing the ability to generate reports.
Subtasks:

Design an admin dashboard with access to user profiles, job postings, and activity logs.
Implement CRUD (Create, Read, Update, Delete) operations for user profiles and job postings.
Develop a system for tracking user activities and generating reports.
Story Points: 5   Priority Level: High

**Comment by chetanpanchal27** [comment]
Started creating Admin Panel

**Comment by ravi2799** [comment]
I have added frontend for to show list of employers in admin panel.

**Comment by Umang070** [comment]
#33 I have implemented functionality in which the admin can delete the employer from the list and all the posts posted by the employer and all the applications for that posts are also deleted from the database.

**Comment by ravi2799** [comment]
Admin panel is working. I am closing this issue.
