### ISSUE TITLE
US 7 -  Student/Candidate - Build/Upload Resume

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#34]
**As a student/candidate, I want to be able to create or upload my resume to showcase my skills and experience to potential employers. **

Acceptance Criteria:

An interface should be implemented to upload the resume.
Students should be able to upload resumes in various formats e.g. PDF and JPG format.
After clicking on the upload button, the resume should be uploaded successfully in the database.
Subtasks:

Design a resume-building/uploading feature with fields for personal information, education, work experience, skills, etc.
Implement a resume storage mechanism to save the resume data.
Allow students to edit and update their resumes as needed.
Story Points: 3   Priority Level: High

**Comment by chetanpanchal27** [comment]
Started working on this issue.

**Comment by urvishkapadiya** [comment]
#44  US-7 Student/Candidate - Build/Upload Resume-jpeg has been done.(Backend). Front end team please verify after integrating it with front end part.

**Comment by Umang070** [comment]
#34 US 7 - Student/Candidate - Build/Upload Resume has been completed so the User can upload, edit and view the resume.
