### ISSUE TITLE
US9- Student/Candidate - Track Applications

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#35]
As a student/candidate, I want to be able to track the status of my job applications, so that I can stay updated on the progress.

Acceptance Criteria:

The Tracking system should display the status of the application.
Notify if selected for the interview.
The Tracking system should display updates made by the recruiter on the application. Subtasks:
Design a dashboard or notification system to display the status of job applications.
Implement a mechanism for employees to update the application status.
Allow students to view the status of their applications.
Story Points: 3   Priority Level: Medium

**Comment by urvishkapadiya** [comment]
#US9 Student/Candidate - Track Applications has been done with the previous commit as the track application mechanism depends after user apply to the job. (Backend)

**Comment by Umang070** [comment]
#35 For the UI part, there is a separate section in which the user can track all the applied applications with some defined labels like (applied, shortlisted, rejected, accepted, etc) and for the employer also there is a section where he/she can see all the applications for particular posted job.
