### ISSUE TITLE
US10 - Employer - Browse Candidates

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#36]
As an employer, I want to be able to search and browse through the profiles of job-seeking candidates, so that I can find potential candidates for my job offers.

Acceptance Criteria:

Employers should be able to access the complete profile details of a candidate from the search results.
All the relevant jobs should be fetched from the database.
Subtasks:

Design a user-friendly interface for browsing candidate profiles.
Implement a search functionality to allow employers to filter candidates based on criteria such as skills, experience, or location.
Fetch and display candidate profiles from the database.
Story Points: 3   Priority Level: Medium

**Comment by urvishkapadiya** [comment]
#40 US-10,Subtask : Development -"Student should be able to apply for a job posted by the recruiter" has been done. (Backend) ,
Frontend team please integrate it.

**Comment by Umang070** [comment]
US-10, Subtask: Development -"Student should be able to apply for a job posted by all the recruiters" has been completed. (frontend) and remaining task (browse candidate pending)

**Comment by urvishkapadiya** [comment]
US-10, All the task of Employer - Browse Candidates has been done. (Backend)

**Comment by Umang070** [comment]
US-10, Now Employers can see the applicants who applied for particular jobs. (frontend)
