### ISSUE TITLE
US11 - Add functionality to select Candidates for Interview

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#37]
**As an employer, I want to be able to review the applications received for a job offer and select candidates for interviews. **

Subtasks:

Create a dashboard or notification system to alert employers about new applications.
Develop a user interface for reviewing candidate applications.
Implement a selection mechanism for shortlisting candidates for interviews.

Story Points: 3   Priority Level: Medium

**Comment by Umang070** [comment]
#37 US11 - Add functionality to select Candidates for Interviews has been done.  Employers can shortlist the candidate and select or reject the candidate.

**Comment by Kenish14** [comment]
The function added is working fine and tested. Closing the issue.
