### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#51]
Setup ci/cd pipeline for devlopment

**Comment by dvijbarot** [comment]
As per discussions in the team meeting, we have finalized the usage of Github Actions as our Continuous Integration/Continuous Deployment (CI/CD) management tool.

**Comment by Kenish14** [comment]
For Automation Tests we are using PlayWright tool

**Comment by chetanpanchal27** [comment]
CI/CD has been successfully implemented and completed.
