### ISSUE TITLE
Unit testing of System

### ISSUE THREAD

**Issue by ravi2799** [chetanpanchal27/Techno-Sync-soen6011summer2023#52]
The aim is to test the implemented functionality.

**Comment by dvijbarot** [comment]
Beginning tests as per discussion and approval from core development team.

**Comment by Kenish14** [comment]
Functionalities working as per the requirements and passes the acceptance criteria

**Comment by urvishkapadiya** [comment]
#54 Have done with the unit testing of the main functionality using JEST Library. No bugs found so far.
